"""Pydantic I/O models for the BAO Service (Service 5 — Beam Angle Optimization).

BAO chooses *which* beam directions to use before fluence optimization runs. The
search is built on top of Service 4: a candidate set of beam angles is scored by
how good a plan it produces — i.e. build a beam model for those angles, run a
(short) fluence optimization, and take the achieved composite cost as the score
(lower is better). A search strategy then selects the best ``n_beams`` subset.

The request reuses :class:`EngineSpec` (from ``models/dose.py``) and
:class:`ObjectiveSpec` (from ``models/optimization.py``) so BAO, Optimization,
and Dose all agree on engine pinning and clinical-goal semantics. The cache key
mirrors the other services: SHA256 of a normalized JSON view, excluding transient
fields (``plan_id``, timestamps).
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, model_validator

from .dose import EngineSpec
from .job import JobState
from .optimization import ObjectiveSpec


class CandidateAngle(BaseModel):
    """One candidate beam direction (gantry + couch, degrees)."""

    gantry_deg: float = Field(..., ge=0.0, lt=360.0)
    couch_deg: float = Field(default=0.0, ge=0.0, lt=360.0)

    def key(self) -> str:
        return f"{self.gantry_deg:.3f}/{self.couch_deg:.3f}"

    def hash(self) -> str:
        return hashlib.sha256(self.key().encode("utf-8")).hexdigest()[:12]


class BAOStage(str, Enum):
    """Stages a :meth:`BAOService.run` call passes through."""

    queued = "queued"
    loading = "loading"
    enumerating = "enumerating"
    scoring = "scoring"
    selecting = "selecting"
    persisting = "persisting"
    done = "done"


class BAORunRequest(BaseModel):
    """Input for ``POST /api/v1/bao/run``.

    Candidate angles are either supplied explicitly (``candidate_angles``) or
    generated by sweeping the gantry in ``angle_step_deg`` increments crossed
    with ``couch_angles``. The selected ``n_beams`` are the subset the search
    strategy returns.
    """

    plan_id: Optional[str] = Field(default=None, max_length=36)
    geometry_id: str = Field(..., min_length=1, max_length=36)
    modality: str = Field(default="PROTON_PBS")
    machine_model_id: str = Field(default="default")
    dose_engine: EngineSpec
    objectives: List[ObjectiveSpec] = Field(..., min_length=1, max_length=256)
    n_beams: int = Field(..., ge=1, le=64)

    candidate_angles: Optional[List[CandidateAngle]] = Field(
        default=None, max_length=512,
        description="Explicit candidate set; omit to generate from angle_step_deg.",
    )
    angle_step_deg: Optional[float] = Field(
        default=None, gt=0.0, le=180.0,
        description="Gantry sweep increment when candidate_angles is omitted.",
    )
    couch_angles: List[float] = Field(
        default_factory=lambda: [0.0], max_length=32,
        description="Couch angles crossed with the generated gantry sweep.",
    )

    scoring: str = Field(
        default="fluence_proxy",
        description='Per-angle-set scoring method (currently "fluence_proxy").',
    )
    search: str = Field(
        default="greedy",
        description='Subset-selection strategy: "greedy" or "top_k".',
    )
    scoring_iterations: int = Field(
        default=30, ge=1, le=10_000,
        description="Fluence-optimization iteration budget per scoring run.",
    )
    isocenter_mm: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])

    _ALLOWED_SCORING = {"fluence_proxy"}
    _ALLOWED_SEARCH = {"greedy", "top_k"}

    @model_validator(mode="after")
    def _check(self) -> "BAORunRequest":
        if self.scoring not in self._ALLOWED_SCORING:
            raise ValueError(
                f"scoring must be one of {sorted(self._ALLOWED_SCORING)}, "
                f"got {self.scoring!r}"
            )
        if self.search not in self._ALLOWED_SEARCH:
            raise ValueError(
                f"search must be one of {sorted(self._ALLOWED_SEARCH)}, "
                f"got {self.search!r}"
            )
        if self.candidate_angles is None and self.angle_step_deg is None:
            raise ValueError(
                "provide candidate_angles or angle_step_deg to define the "
                "candidate set"
            )
        return self

    def resolve_candidates(self) -> List[CandidateAngle]:
        """Materialize the candidate angle set (explicit or generated)."""
        if self.candidate_angles is not None:
            return list(self.candidate_angles)
        out: List[CandidateAngle] = []
        g = 0.0
        while g < 360.0 - 1e-9:
            for c in self.couch_angles:
                out.append(CandidateAngle(gantry_deg=round(g, 3), couch_deg=c))
            g += self.angle_step_deg
        return out

    def compute_cache_key(self) -> str:
        cands = self.resolve_candidates()
        payload = {
            "geometry_id": self.geometry_id,
            "modality": self.modality,
            "machine_model_id": self.machine_model_id,
            "engine": {
                "name": self.dose_engine.name,
                "version": self.dose_engine.version,
                "params": self.dose_engine.params,
            },
            "objectives_hash": [o.hash() for o in self.objectives],
            "n_beams": self.n_beams,
            "candidates": [c.key() for c in cands],
            "scoring": self.scoring,
            "search": self.search,
            "scoring_iterations": self.scoring_iterations,
            "isocenter": [round(x, 6) for x in self.isocenter_mm],
        }
        blob = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(blob.encode("utf-8")).hexdigest()


class AngleScore(BaseModel):
    """The score achieved by one candidate angle (or angle set), lower=better."""

    gantry_deg: float
    couch_deg: float
    score: float


class BAOSelectionStep(BaseModel):
    """One forward-selection step (greedy search)."""

    step: int = Field(..., ge=0)
    added_gantry_deg: float
    added_couch_deg: float
    combined_score: float


class BAOResult(BaseModel):
    """Output of a completed beam-angle optimization."""

    bao_id: str
    cache_key: str
    selected_angles: List[CandidateAngle]
    per_angle_scores: List[AngleScore] = Field(default_factory=list)
    selection_history: List[BAOSelectionStep] = Field(default_factory=list)
    final_score: float
    beam_model_id: Optional[str] = None
    compute_time_s: float = Field(..., ge=0.0)
    geometry_id: str
    engine_name: str
    engine_version: str
    scoring: str
    search: str
    created_at: Optional[datetime] = None


class BAOJobStatus(BaseModel):
    """Status row for an async ``POST /bao/run``."""

    id: str
    cache_key: str
    state: JobState = JobState.queued
    progress: float = 0.0
    stage: Optional[BAOStage] = BAOStage.queued
    message: Optional[str] = None
    bao_id: Optional[str] = None
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


__all__ = [
    "CandidateAngle",
    "BAOStage",
    "BAORunRequest",
    "AngleScore",
    "BAOSelectionStep",
    "BAOResult",
    "BAOJobStatus",
]
